Second draft
arfc/2019-park-global pull request #4
Opened 2019-02-27 06:25 UTC by smpark7

This is my second draft for review.

Addresses #3

2019-02-27 15:24 UTC, katyhuff requested changes
Why so much passive voice?
In #2 I expressed that there was too much passive voice in the first draft.
This PR (which was supposed to address #2, not #3 by the way... ) seems to go entirely in the other direction, adding passive voice where active voice used to appear.... What is going on? I stopped reading halfway through because it's clear my previous comment was not addressed. Please fix this before the next request for a review.

2019-02-27 15:24 UTC, katyhuff commented on abstract.tex
> +This abstract presents the outline for the code-to-code verification of Moltres.
What does it mean for an abstract to present an *outline* of verification?

2019-02-27 15:24 UTC, katyhuff commented on abstract.tex
> +Moltres \cite{lindsay_introduction_2018} is an open source coupled neutronics/thermal hydraulics simulation tool for simulating molten salt reactors (MSR).
consider using the glossaries package for auto-expanding acronyms.

2019-02-27 15:24 UTC, katyhuff commented on abstract.tex
> +Strong coupling between neutronics and thermal-hydraulics modeling is an important requirement for new MSR simulation tools due to the strong temperature reactivity coefficients arising from Doppler
Sentence is too convoluted. 
```suggestion
MSR simulation tools must capture strong coupling between neutronics and thermal-hydraulics exhibited by delayed neutron precursor movement as well as strong Doppler and density feedbacks in the fuel salt.
```

2019-02-27 15:24 UTC, katyhuff commented on abstract.tex
> +The development of novel simulation tools for MSRs is an essential step towards understanding the behaviour of MSRs under various conditions, one of which is the changing fuel compositions across the
unnecessary passive voice.

2019-02-27 15:24 UTC, katyhuff commented on abstract.tex
> +The fuel composition in an MSR continuously evolves over time as online refueling replenishes fissile material while removing fission product poisons. The impact of changing fuel composition on the s
```suggestion
The fuel composition in an MSR continuously evolves over time as online refueling replenishes fissile material while removing fission product poisons. The impact of changing fuel composition on the safety parameters such as the reactivity feedback coefficient must be fully characterized to establish a licensing case for this class of reactors.
```

2019-02-27 15:24 UTC, katyhuff commented on abstract.tex
> +Moltres is an application code built in the MOOSE finite element framework \cite{gaston_moose:_2009}.
- unnecessary passive voice.
- don't use the word "code" in this way.  (application is a noun... there's no reson to add the word code... and "software package" or "computational tool" or similar is preferable to "code" )

2019-02-27 15:24 UTC, katyhuff commented on abstract.tex
> +Moltres is developed as a solver for the coupled multi-group neutron diffusion, temperature and delayed neutron precursor governing equations.
unnecessary passive voice.

2019-02-27 15:24 UTC, katyhuff commented on abstract.tex
> +MOOSE is a parallel framework and it has an adaptive meshing scheme.
Unnecessary passive voice. These sentences are also very monotonous when stacked back to back in this way.. "Moltres is... Moltres is.... MOOSE is..." Try reading them aloud and you'll see what I mean..

2019-02-27 15:24 UTC, katyhuff commented on abstract.tex
> +Therefore, reactor simulations with large complex meshes can scale effectively when run on multiple cores.
This sentence is a bit of a "so what". (connect this sentence to the topic of your abstract.)

2019-02-27 15:24 UTC, katyhuff commented on abstract.tex
> +The Molten Salt Fast Reactor (MSFR) is the MSR model used for the code-to-code verification.
Why so much passive voice??!?!?!?!!?
In #2 I expressed that there was too much passive voice in the first draft.
This PR (which was supposed to address #2, not #3 by the way... ) seems to go entirely in the other direction, adding passive voice where active voice used to appear.... What is goign on? I am going to stop reading here. Please fix this before the next request for a review.

2019-02-28 23:10 UTC, smpark7 commented
I apologize for the passive voice sentences. I was trying to remove them but I failed to recognize them and inadvertently added more.

2019-03-02 02:49 UTC, smpark7 commented
The deadline has been extended until 15 march.

2019-03-11 20:31 UTC, katyhuff commented
I will merge this and submit corrections with a PR. Please do not submit until that (upcoming) PR is merged.

2019-03-11 20:31 UTC, merged